#=========================== Filebeat inputs =============================
filebeat.inputs:

  #------------------------------ Log input --------------------------------
  - type: log
    enabled: true
    paths:
      - /target/logs/*.log
    exclude_files: ['.gz$']

# ================================== Outputs ===================================

# ------------------------------ Logstash Output -------------------------------
output.logstash:
  enabled: true
  hosts: ["10.10.101.110:5044"]
